"""Create the base Migration

Revision ID: 11761fc744aa
Revises: 
Create Date: 2023-12-20 08:09:44.813602

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models import Tenant, Chatbot

# revision identifiers, used by Alembic.
revision: str = '11761fc744aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Tenant.__table__.create(op.get_bind().engine)
    Chatbot.__table__.create(op.get_bind().engine)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Tenant.__table__.drop(op.get_bind().engine)
    Chatbot.__table__.drop(op.get_bind().engine)
    # ### end Alembic commands ###
